### ISSUE TITLE
Failed to get `modelfox` as a dependency of package

### ISSUE THREAD

**Issue by joelchen** [modelfoxdotdev/modelfox#123]
After this commit (https://github.com/modelfoxdotdev/modelfox/commit/95683d585843fb32fafde979b45e592ab9c54a3a), cargo build no longer works even after removing /Users/joelchen/.cargo/git and `cargo clean`:
```
error: failed to get `modelfox` as a dependency of package

Caused by:
  failed to load source for dependency `modelfox`

Caused by:
  Unable to update https://github.com/modelfoxdotdev/modelfox

Caused by:
  failed to parse manifest at `/Users/joelchen/.cargo/git/checkouts/modelfox-e35e97cb1dd1c244/cc4dcf6/languages/c/Cargo.toml`

Caused by:
  invalid type: map, expected a sequence for key `package.authors`
```
CC: @deciduously

**Comment by nitsky** [comment]
@joelchen please use the latest nightly which has support for the "workspace inheritance" feature in cargo.
