### ISSUE TITLE
URL in repo description is broken

### ISSUE THREAD

**Issue by skewballfox** [modelfoxdotdev/modelfox#124]
hey, probably just a heads up in case you weren't aware of this, but currently the url listed in the description of the repo and your github profile (www.modelfox.dev) isn't reachable.

**Comment by nitsky** [comment]
@skewballfox we are migrating the service to this domain now, hopefully it will be up again soon! Sorry for the inconvenience.

**Comment by skewballfox** [comment]
no worries, I just wanted to make sure that you guys were aware of it.
