### ISSUE TITLE
Running `modelfox app` gives "error: No such file or directory (os error 2)"

### ISSUE THREAD

**Issue by Chuxiaof** [modelfoxdotdev/modelfox#127]
I am following [your tutorial](https://www.modelfox.dev/docs/getting_started/inspect), which asks me to run `modelfox app`, but it doesn't look right:

```
$ modelfox app
error: No such file or directory (os error 2)
```

This isn't very informative, so I did a quick check with `dtruss`

```
$ sudo dtruss -t open modelfox app
SYSCALL(args)            = return
error: No such file or directory (os error 2)
open("/Users/qys/Library/Application%20Support/modelfox/db/modelfox.db\0", 0x1000601, 0x1B6)             = -1 Err#2
```

Looks like you are URL-escape the path. I assume the `Application%20Support` segment should be `Application Support` instead?

**Comment by nitsky** [comment]
This has been fixed on master and will be included in the next release. Thanks!
